---
- hosts: all
  become: true
  tasks:
  - name: install python-pip
    yum:
     name: python-pip
     state: present
  - name: install docker-py python module
    pip:
     name: docker-py
     state: present
  - name: docker start
    docker_container:
     image: rosebalu/wordpress:words
     name: container
     state: started
     published_ports:
      - 0.0.0.0:8090:8080

