---
- hosts: localhost
  become: true
  tasks:
  - name: install docker
    yum:
     name: docker
     state: present
  - name: Start docker service
    service:
     name: docker
     state: started
  - name: login to registry
    shell: docker login -u rosebalu -p Rosebalu@2022
  - name: pull an image
    shell: docker pull rosebalu/wordpressimage:wordpress1
